kalessil/phpinspectionsea

docs/architecture.md

See #134. Attempted to make the text more English friendly while staying true to the content as much as possible. Please review the changes and let me know if I changed the meaning of something.
Furthermore, I'd like to discuss/ask the purpose of this document.

Architecture document review.

---

META-INF/plugin.xml
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeSmell/DisallowWritingIntoStaticPropertiesInspector.java
src/main/resources/inspectionDescriptions/DisallowWritingIntoStaticPropertiesInspection.html
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/controlFlow/DisallowWritingIntoStaticPropertiesInspectorTest.java
src/test/resources/fixtures/controlFlow/disallow-any-write-into-static-property.php
src/test/resources/fixtures/controlFlow/disallow-write-into-static-property-default.php

Here is prototype of the inspection. This is my vision of how it should work. If anyone have suggestions do not hesitate to write a comment. 
Some steps that I want to do before merge:
- Write tests
- Improve message and description
- Decide if this inspection should produce Warning by default.

#31 Disallow writing into static properties

---

.gitignore
.idea/workspace.xml

@kalessil you accidentally add workspace.xml =) I try to fix this problem

Add .gitignore Remove idea/workspace.xml from the git.

---

docs/DEVELOPERS.md

Fix DEVELOPERS.md typo on repo url

---

docs/DEVELOPERS.md

Improve developer documentation

---

docs/DEVELOPERS.md
docs/code-style.md
docs/control-flow.md
docs/performance.md
docs/probable-bugs.md
docs/security.md
docs/types-compatibility.md

Make consistent use of header through all pages.

Add consistency to page headers

---

docs/security.md

This PR updates some of the text in security.md in order to improve readability/clarity. Thanks for providing this plugin!

Grammatical improvements in security.md

---

RULES.md
docs/types-compatibility.md
src/main/resources/inspectionDescriptions/GenericObjectTypeUsageInspection.html
src/main/resources/inspectionDescriptions/TypeUnsafeArraySearchInspection.html
src/main/resources/inspectionDescriptions/TypeUnsafeComparisonInspection.html

Hi guys,
please could you review this. Specially the section related to "generic objects". I need external references, this section is very opinionated (mine) since I was not able to find any external refs specifically for the case.
If someone can provide more resources, please feel free, feedback is welcome. I can take care of rewriting later on.
This PR takes care of the RULES in *Inspections Lists (Type compatibility)*

Docs Updates

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/CallableInLoopTerminationConditionInspector.java
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/semanticalAnalysis/CallableInLoopTerminationConditionInspectorTest.java
src/test/resources/fixtures/semanticalAnalysis/callable-inloop-condition.fixed.php
src/test/resources/fixtures/semanticalAnalysis/callable-inloop-condition.php

[#309] QF to callables at conditionals on for()

---

META-INF/plugin.xml
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeSmell/ComparisonOperandsOrderInspector.java
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/options/OptionsComponent.java

[#288] ComparisonOperandsOrderInspector: avoid double-disabling

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/dateTime/DateIntervalSpecificationInspector.java
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/pitfalls/DateIntervalSpecificationInspectorTest.java
src/test/resources/fixtures/pitfalls/date-interval-specification.php

Date interval specification validity: report "PT" as invalid

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/security/SecurityAdvisoriesInspector.java

Add [phpspec](https://github.com/phpspec/phpspec) (a SpecBDD framework) and [Psalm](https://github.com/vimeo/psalm) (a static analysis tool) to the list of dev packages.

SecurityAdvisoriesInspector: add more dev-packages

---

META-INF/plugin.xml
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeSmell/EfferentObjectCouplingInspector.java
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/options/OptionsComponent.java
src/main/resources/inspectionDescriptions/EfferentObjectCouplingInspection.html
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/codeStyle/EfferentObjectCouplingInspectorTest.java
src/test/resources/fixtures/codeStyle/efferent-object-coupling.php

Use this inspection in the project. So I decided to share it with the community.
One thing that I want to implement before merge - edit relations num.
Do not know how to do this with new style of `createOptionsPanel`. 
If this inspection is useful i can continue to work on it.

Implement efferent coupling inspection

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java

As suggested during your talk i created a pr for a forgotten doctrine debug statement. Let me know if i should add anything else to this pr.

added default for forgotten doctrine debug statement

---

docs/types-compatibility.md

I noticed some basic spelling/grammar errors in this file while reading it. There are still a lot of sentences that can be cleaned up further, but I tried to keep edits simple for this PR :)

Minor typo fixes in types-compatibility.md

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java

Here you are. After building it, I was able to test it in PHPstorm successfully

[#559] ForgottenDebugOutputInspector: more debug functions (XDebug)

---

docker/Dockerfile
docker/README.md
docker/entrypoint.sh
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/magicMethods/strategy/NormallyCallsParentMethodStrategy.java

Please see the README.md. Works for me :-)

Experimental docker headless PHPStorm configuration

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/foreach/ForeachSourceInspectorTest.java
src/test/resources/fixtures/foreach/foreach-source-false-positives.php

* 1d2ff48: bugfix;
* Actually it was just a simple `if()` for negate the `types.contains(Types.strArray)`;
* 2b57488: updated the code-style;
* L155: Fixed non-null argument;
* `String.replace()` was changed to `String.format()`;

Fixes #800: cannot iterate over class array

---

docs/DEVELOPERS.md

Updated language to be more supportive and fixed some English idiosyncrasies. 
This was done after finding Issue #1084 posted by @kalessil 
Should be slightly more friendly to new developers now!

Update DEVELOPERS.md in accordance with #1084

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/loops/LoopWhichDoesNotLoopInspector.java
testData/fixtures/controlFlow/loop-does-not-loop-false-positives.php

Failed to setup environment locally for running tests, so sent PR to run CI.

Mark iterable as special case for `LoopWhichDoesNotLoopInspection` #1662

---

docs/security.md

as PHP_VERSION_ID >= 70000 and already [] on that line for the inner.
one whitespace issue on the last line?

minor cs-fix: array() -> []

---

docs/architecture.md
docs/control-flow.md
docs/getting-started.md
docs/performance.md
docs/probable-bugs.md
docs/unused.md

Correct some spelling and grammar issues in the markdown documents.

spelling: Correct some spelling and grammar issues
