kalessil/phpinspectionsea

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/ReferenceMismatchInspector.java
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/utils/TypeFromPlatformResolverUtil.java

that method was not needed and is dropped in 2017.

proper use of type API

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/languageConstructions/ClassConstantCanBeUsedInspector.java
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/lang/ClassConstantCanBeUsedInspectorTest.java

Fixes Issue #183 that I reported a week and a half ago
I'd love to contribute more, ~~~maybe write a test for this, but I couldn't run any of the tests. I got a weird message about not being able to find bundle messages.CssBundle when I tried to run the tests? I ended up figuring out how this worked and debugging by copying the popupBox you use for updates and using the title for debugging information~~~
Edit: I didn't follow your docs for setting up a dev environment (didn't even know they were there, thanks), so I didn't end up adding the CSS lib from PHPStorm, just the PHP and PHPStorm Lib (Because they were already in the settings, just pointing to a bad path)

Adding a check to make sure that the use statement isn't a class trait

---

META-INF/plugin.xml
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeSmell/UsageOfSilenceOperatorInspector.java
src/main/resources/inspectionDescriptions/UsageOfSilenceOperatorInspection.html
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/codeStyle/UsageOfSilenceOperatorInspectorTest.java
src/test/resources/fixtures/codeStyle/usage-of-silence-operator.php

Todo
Here is the list of functions that are used with `at` operator from the symfony repository:
| Num | Function name                   |
| --- |:--------------------------------|
| 221 |   trigger_error                 |
| 82  |   unlink                        |
| 36  |   mkdir                         |
| 17  |   chmod                         |
| 12  |   rmdir                         |
| 9   |   rename                        |
| 8   |   fsockopen                     |
| 8   |   json_encode                   |
| 7   |   file_put_contents             |
| 6   |   fwrite                        |
| 6   |   fopen                         |
| 6   |   posix_isatty                  |
| 6   |   filemtime                     |
| 4   |   touch                         |
| 4   |   iconv …

prototype #186 Reports the usage of 'at' operator

---

src/test/java/com/kalessil/phpStorm/phpInspectionsEA/api/IsEmptyFunctionUsageInspectorTest.java
src/test/resources/fixtures/api/empty-function.php

I've added a test, and in this test I've discovered a bug (That I'm going to make a shot at fixing). I'm not sure if it's a Php Inspections Bug, but the warning produced for `isIntNull` is wrong. It doesn't detect `$int` as an integer or a nullable for some reason, or it gives the weak warning of `empty` allowing too many things through.

Adding a test for IsEmptyUsage Inspector

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/OnlyWritesOnParameterInspector.java
src/test/resources/fixtures/deadCode/parameters-writes-only.php

What I did was basically removes the `if()` that avoids any validation over _referenced variables_, before it checks if it was used inside the function. 
Now the `analyzeAndReturnUsagesCount` will receives an observation that the passed variable is a _referenced variable_. It'll allows that this method checks if the variable is used internally, and independently of it be a reference, it'll returns 0 if it is never used (registering the problem). After that, if the variable is a referenced variable, then all method could be avoided (once that is useful only for local variables).
Added some tests to make sure that I don't broke anything.

[#188] OnlyWritesOnParameterInspector: check if referenced variables are use()d too

---

README.md

Currently the Project Images are linking to the source of the image which is not that useful. This commit adds links to the actual projects's website.

Add direct links to Acknowledged Projects

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/security/SecurityAdvisoriesInspector.java

I've added 2 more packages which should be required as dev dependency. Couldn't think of more commonly used packages at the moment. 
I've did a quick scroll through https://github.com/exakat/php-static-analysis-tools, you might find one or two more.

Add some additional dev packages to the securityAdvisories check

---

META-INF/plugin.xml
RULES.md
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeStyle/SelfClassReferencingInspector.java
src/main/resources/inspectionDescriptions/SelfClassReferencingInspection.html
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeStyle/SelfClassReferencingInspectorTest.java
src/test/resources/fixtures/codeStyle/self-class-referencing.fixed.php
src/test/resources/fixtures/codeStyle/self-class-referencing.php
src/test/resources/fixtures/codeStyle/self-class-referencing.reverse.fixed.php
src/test/resources/fixtures/codeStyle/self-class-referencing.reverse.php

It fixes #146 
@funivan is copyrighted because of his helpful comments;

[#146] References by "new self" instead of "new MyClass"

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/classes/LongInheritanceChainInspector.java

`CComponent` is root class in yii1.

Don't report over inheritance for yii1 components

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java

Hi Vladimir,
Thanks a lot for this plugin - it simply takes my code to a whole new level!
I work in Drupal projects quite a lot, and use Drupal-specific debug functions (similar to Laravel `dd`) quite a lot. It would be great if they could be marked as Forgotten Debug Output warnings too. I understand one can easily add new functions, but I think they can benefit everyone who uses Drupal with PHPStorm. 
They are global functions (yuck), so I totally understand if you don't feel like adding them to the list and reject this PR. 
Function reference: https://api.drupal.org/api/devel/devel.module/7.x-1.x

Add Drupal debug functions: dpm/dsm, dvm, kpr and dpq to ForgottenDebugOutputInspector

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/UnqualifiedReferenceInspector.java
src/test/resources/fixtures/unqualified-function-refs-ns.php

Afaik it doesn't enable `opcache` optimizations but `opcode` optimizations.

UnqualifiedReferenceInspector: fix message wording

---

.github/stale.yml

`closeComment` must be a string, like `markComment`, otherwise it causes an error and issues will never be closed.

Fix stale config

---

META-INF/plugin.xml
RULES.md
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/languageConstructions/BacktickOperatorUsageInspector.java
src/main/java/com/kalessil/phpStorm/phpInspectionsEA/openApi/BasePhpElementVisitor.java
src/main/resources/inspectionDescriptions/BacktickOperatorUsageInspection.html
src/test/java/com/kalessil/phpStorm/phpInspectionsEA/lang/BacktickOperatorUsageInspectorTest.java
src/test/resources/fixtures/lang/backtick-operator.fixed.php
src/test/resources/fixtures/lang/backtick-operator.php

* 2dfdc9e: inspection implementation;
* a1321d9: quick-fix implementation;
* 3e806b9: code-style updated;
* Methods `isTestContext()` and `isFromRootNamespace()` was modifed to be `static`;
It will converts to `shell_exec("double-quoted")` once that single-quotes will not supports variables inside backticks. In future we can try identify better quote style based on backtick contents.

Feature #797: avoid backtick operator usage

---

docs/probable-bugs.md

Below was the only sentence I didn't quite understand enough to work with:
> PHP´s magic [`::class`-constant](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) will not 
> canonical the casing of your imports.

Probable bugs doc review.

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/magicMethods/MagicMethodsValidityInspector.java

This is my first contribution to a java project, so please be kind! :)
This PR fixes Issue #1106, by creating an array of "legacy" classes that can be tested against the found method. If the current class extends a legacy class and the method has a parent there, then it will not trigger the "Only magic methods should start with '__'" error message.
Hope it helps! :)

Issue #1106 - overwriting methods starting with __ from legacy classes

---

docs/performance.md

Replace empty array initialization with empty array during the final array_merge call.
This might be controversial and personnel preference but I find the empty array initialization is not obvious  and can better be moved down to the actual `array_merge` call.

Improve "Slow array function used in loop" example readablillity

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/PrintfScanfArgumentsInspector.java
testData/fixtures/api/printf-scanf.php

scanf methods also support suppresing placeholder assignment with asterisk. Patterns using asterisk are currently reported as invalid and reported with argument count mismatch.

added support for suppressed placeholders

---

.github/FUNDING.yml

Since you are not enrolled to GitHub sponsoring program (I'm not aware of a single developer who's enrolled), github is better to be removed from the list.

Remove github since you're not enrolled into sponsorship program

---

.github/FUNDING.yml

For comapnies it is easier to donate through a single transaction over PayPal than to get the buy-in for a subscription-like donation through Patreon.

Add PayPal donation link

---

docs/performance.md

Since PHP 7.4, array_merge can be called without any argument:
https://www.php.net/manual/en/function.array-merge.php#refsect1-function.array-merge-changelog
This was made specifically to allow the spread operator to work when the array is empty.
It is now no longer required to add an empty array to the mix

update docs with new syntax permitted with PHP7.4

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/classes/DeprecatedConstructorStyleInspector.java

Hinting "deprecated constructor" on the function `Foo` is not validate as i would think
```
class Foo {
public static function Foo() {}
}
```

deprecated constructor inspection should not hint static method with same as class name

---

testData/fixtures/deadCode/parameters-writes-only.php

Hi. Today we're plan to release first PhpStorm 2020.2 EAP. In this version simple "always-false" instructions will not be reachable from control flow entry point anymore, since they're considered as unreachable code (as if there was 'return' for instance). This PR changes testData to make test pass, but please feel free to tune inspection code.

Update testData according to PhpStorm Control Flow engine changes

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/languageConstructions/nullCoalescing/IssetArgumentExistenceInspector.java

Addresses: #1628 
Here is a list of all reserved variables.
https://www.php.net/manual/en/reserved.variables.php
I don't know if any of the other more known variables is affected as well or filtered out differently.

Added $http_response_header to the list of reserved variables

---

src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/security/SecurityAdvisoriesInspector.java
testData/fixtures/securityAdvisories/devDependenciesInProdPackage/composer.json
testData/fixtures/securityAdvisories/hasAdvisories/composer.json
testData/fixtures/securityAdvisories/needsAdvisoriesCreatesNewSection/composer.fixed.json
testData/fixtures/securityAdvisories/needsAdvisoriesCreatesNewSection/composer.json
testData/fixtures/securityAdvisories/needsAdvisoriesUsesExistingSection/composer.fixed.json
testData/fixtures/securityAdvisories/needsAdvisoriesUsesExistingSection/composer.json
testData/fixtures/securityAdvisories/needsMasterAdvisories/composer.json

Hello,
I updated the [roave/security-advisories ](https://github.com/Roave/SecurityAdvisories) requirement to use `dev-latest` instead of `dev-master` as it has been changed by the maintainers, cf: https://github.com/Roave/SecurityAdvisories/commit/5ae6aa6482b72946bc0d279c3b54dc1dbeae68d8
Cheers.

Update roave/security-advisories requirement
